---
title: "Theta calculation"
author: "Jinliang Yang"
date: "02-03-2022"
output: NULL
---

## Path Normalization

````{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('..//')) 
#library(tidyverse)
```


# Wright Fisher function


```{r}
wright_fisher <- function(N=1000, A1=100, t=1000){
  p <- A1/(2*N)
  ### make a numeric vector to hold the results
  freq <- as.numeric();
  t=1000
  ### Use for loop to run over t generations
  for (i in 1:t){
    A1 <- rbinom(1, 2*N, p)
    p <- A1/(2*N)
    freq[i] <- p
  }
  return(freq)
}
```

---

## Apply the function 
```{r}
set.seed(1234587)
sim1 <- wright_fisher(N=50, t=1000, A1=20)
plot(sim1[1:100], type="o", pch=19, xlab="Generations", ylab="A1 allele count")
```

## Apply the function to conduct 1000 simulations

```{r}
set.seed(1234)
frq <- wright_fisher(N=1000, A1=500, t=1000)
pdf("graphs/sim1000_0.5.pdf", width=8, height=8)
plot(frq, type="l", ylim=c(0,1), col=3, xlab="Generations", ylab=expression(p(A[1])))
    for(u in 1:1000){
      frq <- wright_fisher(N=1000, A1=100, t=1000)
      random <- sample(1:1000,1,replace=F)
      randomcolor <- colors()[random] 
      lines(frq,type="l",col=(randomcolor))
    }
dev.off()

```

----------------

# Login onto cluster

```{bash}
ssh USERID@crane.unl.edu # DUO to activate it
```

```{bash}
srun --qos=short --nodes=1 --licenses=common --ntasks=1 --mem 2G --time 2:00:00 --pty bash
```

And then cd to your repo

```{bash}
cd $COMMON
```

Then update your repo

```{bash}
git clone git@github.com:YOURID/2022-agro932-lab.git
```

otherwise

```{bash}
git pull
cd largedata
```


----------------

# Install a software on crane


----------------

# Calculate theta values

```{r}
frq <- read.table("data/frq.txt")
names(frq) <- c("chr", "pos", "af")
hist(frq$af, col="blue", xlab="allele freq", main="allele freq spectrum")
```
### theta pi
```{r}
pi <- function(n=10, p=0.1){
  return(n/(n-1)*(1-p^2-(1-p)^2))
}
pi(n=10, p=0.1)
```

### use for loop to calculate pi for all SNP sites

```{r}
frq$pi <- 0
for(i in 1:nrow(frq)){
  frq$pi[i] <- pi(n=5, p=frq$af[i])
}

plot(x=frq$pos, y=frq$pi, type="o", xlab="Physical Position", ylab="Theta pi")
```


### SFS

```{r}
frq$new <- round(frq$af, 1)
sfs <- table(frq$new)

barplot(sfs, col="#cdc0b0", xlab="A1 allele frequency", 
        ylab="No. of segregating sites", 
        cex.axis =1.5, cex.names = 1.5, cex.lab=1.5)
```


